version: '3.7'

services:
  vault:
    image: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    command: vault server -dev

  echo-server:
    image: jmalloc/echo-server
    ports:
      - "8080:8080"
    environment:
      - MESSAGE=HelloFromEchoServer

  proxy:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: proxy
